apiVersion: v1
kind: Service
metadata:
  name: container1-network-service
spec:
  selector:
    app: pod-container1-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
